services:
  php:
    image: php:8.0-fpm-alpine
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: catalogue
    networks:
      - backend

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - backend

networks:
  backend:
    driver: bridge